version: '3.1'

services:
  client:
    image: rollthedice:latest
    restart: always
    logging:
      options:
        max-size: "4k"
        max-file: "3"
    ports:
      - 3000:3000
    volumes:
      - "./app:/app"
      - /app/node_modules
